name: Build container release images
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      platforms: linux/amd64
      use_native_arm64_builder: false
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      tags: |
        type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        type=raw,value=edge,enable=${{ github.ref == 'refs/heads/dev' }}
        type=sha
    secrets: inherit

  build-image-streaming:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      platforms: linux/amd64
      use_native_arm64_builder: false
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon-streaming
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      tags: |
        type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        type=raw,value=edge,enable=${{ github.ref == 'refs/heads/dev' }}
        type=sha
    secrets: inherit
